Repository KrishnaKodali99/q-file-share, pull requests merged in 2024-11, with the labels that each got.

#23 New: Prettify all the developed UI files
  q-file-share-ui/README.md
  q-file-share-ui/package-lock.json
  q-file-share-ui/package.json
  q-file-share-ui/src/app/dashboard/dashboard.module.css
  q-file-share-ui/src/app/dashboard/page.tsx
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/app/layout.tsx
  q-file-share-ui/src/app/login/login.module.css
  q-file-share-ui/src/app/login/page.tsx
  q-file-share-ui/src/app/page.tsx
  q-file-share-ui/src/app/sign-up/page.tsx
  q-file-share-ui/src/app/sign-up/signup.module.css
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Button/Button.module.css
  q-file-share-ui/src/elements/Button/index.tsx
  q-file-share-ui/src/elements/Heading/Heading.module.css
  q-file-share-ui/src/elements/Input/Input.module.css
  q-file-share-ui/src/elements/Input/index.tsx
  q-file-share-ui/src/elements/Text/Text.module.css
  q-file-share-ui/src/elements/Text/index.tsx
  q-file-share-ui/src/modules/ActivityCard/ActivityCard.module.css
  q-file-share-ui/src/modules/ActivityCard/index.tsx
  q-file-share-ui/src/modules/Card/index.tsx
  q-file-share-ui/src/modules/ListModule/ListModule.module.css
  q-file-share-ui/src/modules/ListModule/index.tsx
  q-file-share-ui/src/modules/LoginForm/LoginForm.module.css
  q-file-share-ui/src/modules/LoginForm/index.tsx
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
  q-file-share-ui/src/modules/SignUpForm/SignUpForm.module.css
  q-file-share-ui/src/modules/SignUpForm/index.tsx
  q-file-share-ui/src/utils/index.ts
  q-file-share-ui/src/utils/list-modules-sort/index.tsx
Labels: enhancement, front-end

#17 New: Create list header and add styling
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/assets/filter.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/modules/ListHeader/ListHeader.module.css
  q-file-share-ui/src/modules/ListHeader/index.tsx
  q-file-share-ui/src/modules/index.ts
Labels: enhancement, front-end

#26 New: Develop send file page and corresponding modules
  q-file-share-ui/src/app/dashboard/page.tsx
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/app/login/login.module.css
  q-file-share-ui/src/app/received-files/page.tsx
  q-file-share-ui/src/app/send-file/SendFile.module.css
  q-file-share-ui/src/app/send-file/page.tsx
  q-file-share-ui/src/app/shared-files/page.tsx
  q-file-share-ui/src/app/sign-up/signup.module.css
  q-file-share-ui/src/assets/file-upload.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Input/Input.module.css
  q-file-share-ui/src/elements/Input/index.tsx
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
  q-file-share-ui/src/modules/SendFileOptions/SendFileOptions.module.css
  q-file-share-ui/src/modules/SendFileOptions/index.tsx
  q-file-share-ui/src/modules/UploadFile/UploadFile.module.css
  q-file-share-ui/src/modules/UploadFile/index.tsx
  q-file-share-ui/src/modules/index.ts
Labels: enhancement, front-end

#27 Merging changes to main.
  README.md
  q-file-share-server/.gitignore
  q-file-share-server/README.md
  q-file-share-server/app/db/config.py
  q-file-share-server/app/db/db_session.py
  q-file-share-server/app/models/__init__.py
  q-file-share-server/app/models/user.py
  q-file-share-ui/src/app/dashboard/page.tsx
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/app/login/login.module.css
  q-file-share-ui/src/app/received-files/page.tsx
  q-file-share-ui/src/app/received-files/receivedFiled.module.css
  q-file-share-ui/src/app/send-file/SendFile.module.css
  q-file-share-ui/src/app/send-file/page.tsx
  q-file-share-ui/src/app/shared-files/page.tsx
  q-file-share-ui/src/app/shared-files/sharedFiles.module.css
  q-file-share-ui/src/app/sign-up/signup.module.css
  q-file-share-ui/src/assets/file-upload.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Input/Input.module.css
  q-file-share-ui/src/elements/Input/index.tsx
  q-file-share-ui/src/modules/ActivityCard/ActivityCard.module.css
  q-file-share-ui/src/modules/ListHeader/ListHeader.module.css
  q-file-share-ui/src/modules/ListModule/ListModule.module.css
  q-file-share-ui/src/modules/ListModule/index.tsx
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
  q-file-share-ui/src/modules/SendFileOptions/SendFileOptions.module.css
  q-file-share-ui/src/modules/SendFileOptions/index.tsx
  q-file-share-ui/src/modules/UploadFile/UploadFile.module.css
  q-file-share-ui/src/modules/UploadFile/index.tsx
  q-file-share-ui/src/modules/index.ts
  resources/dashboard-page.png
  resources/login-page.png
  resources/receivedfiles-page.png
  resources/sendfile-page.png
  resources/sharedfiles-page.png
  resources/signup-page.png
  resources/system-flow.jpg
Labels: enhancement

#28 New: Add login API placeholders and new components
  q-file-share-server/README.md
  q-file-share-server/app/api/auth.py
  q-file-share-server/app/auth/__init__.py
  q-file-share-server/app/auth/jwt_handler.py
  q-file-share-server/app/main.py
  q-file-share-server/app/models/user.py
  q-file-share-server/app/utils/__init__.py
  q-file-share-server/app/utils/password_handler.py
  q-file-share-server/main.py
  q-file-share-ui/package-lock.json
  q-file-share-ui/package.json
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/app/login/page.tsx
  q-file-share-ui/src/assets/close-icon.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Input/index.tsx
  q-file-share-ui/src/modules/LoginForm/index.tsx
  q-file-share-ui/src/modules/Notification/Notification.module.css
  q-file-share-ui/src/modules/Notification/index.tsx
  q-file-share-ui/src/modules/SendFileOptions/index.tsx
  q-file-share-ui/src/modules/index.ts
  q-file-share-ui/src/utils/validations/index.ts
Labels: enhancement, front-end, back-end

#32 New: Implement Activity API
  q-file-share-server/app/api/file.py
  q-file-share-server/app/auth/jwt_handler.py
  q-file-share-server/app/models/response_models.py
  q-file-share-server/app/services/file_services.py
Labels: enhancement, back-end
