Repository KrishnaKodali99/q-file-share, pull requests merged in 2024-10, with the labels that each got.

#3 New: Create folder structure for QFS (BE)
  q-file-share-server/app/api/__init__.py
  q-file-share-server/app/db/__init__.py
  q-file-share-server/app/quantum-protocols/dilithium/__init__.py
  q-file-share-server/app/quantum-protocols/kyber/__init__.py
  q-file-share-server/app/quantum-protocols/ntru/__init__.py
  q-file-share-server/app/quantum-protocols/ntru/ntru.py
Labels: enhancement

#5 New: Create SignUpForm module and change indentations (FE)
  q-file-share-ui/src/app/dashboard/dashboard.module.css
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/app/login/page.tsx
  q-file-share-ui/src/app/sign-up/page.tsx
  q-file-share-ui/src/modules/LoginForm/LoginForm.module.css
  q-file-share-ui/src/modules/LoginForm/index.tsx
  q-file-share-ui/src/modules/LoginScreen/index.tsx
  q-file-share-ui/src/modules/SignUpForm/SignUpForm.module.css
  q-file-share-ui/src/modules/SignUpForm/index.tsx
  q-file-share-ui/src/modules/index.ts
Labels: enhancement, front-end

#7 New: Create utils folder (FE)
  q-file-share-ui/src/index.ts
Labels: front-end

#9 Add navbar
  q-file-share-ui/.editorconfig
  q-file-share-ui/src/app/dashboard/page.tsx
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
  resources/web-pages.pdf
Labels: enhancement, front-end

#11 New: Add input and button elements (FE)
  q-file-share-ui/.editorconfig
  q-file-share-ui/.gitignore
  q-file-share-ui/package-lock.json
  q-file-share-ui/package.json
  q-file-share-ui/src/app/dashboard/page.tsx
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/app/login/page.tsx
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Button/Button.module.css
  q-file-share-ui/src/elements/Button/index.tsx
  q-file-share-ui/src/elements/Input/Input.module.css
  q-file-share-ui/src/elements/Input/index.tsx
  q-file-share-ui/src/elements/index.ts
  q-file-share-ui/src/modules/LoginForm/index.tsx
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
  q-file-share-ui/src/utils/index.ts
Labels: enhancement, front-end

#12 Add icons and integrate with NavBar
  q-file-share-ui/src/app/globals.css
  q-file-share-ui/src/assets/logout.svg
  q-file-share-ui/src/assets/qfs-logo.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Button/Button.module.css
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
Labels: enhancement, front-end

#15 New: Create list modules and add styling
  q-file-share-ui/src/modules/ListModule/ListModule.module.css
  q-file-share-ui/src/modules/ListModule/index.tsx
Labels: enhancement, front-end

#18 New : Create Sort functionality and integrate with ListModule
  q-file-share-ui/src/assets/down-arrow.svg
  q-file-share-ui/src/assets/up-arrow.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/modules/ListModule/ListModule.module.css
  q-file-share-ui/src/modules/ListModule/index.tsx
  q-file-share-ui/src/utils/Sort/index.tsx
  q-file-share-ui/src/utils/index.ts
Labels: enhancement, front-end

#20 New: Develop signup page, relevant modules and refactor code
  q-file-share-ui/src/app/login/page.tsx
  q-file-share-ui/src/app/sign-up/page.tsx
  q-file-share-ui/src/app/sign-up/signup.module.css
  q-file-share-ui/src/assets/eye-hide.svg
  q-file-share-ui/src/assets/eye-show.svg
  q-file-share-ui/src/constants/index.ts
  q-file-share-ui/src/elements/Input/Input.module.css
  q-file-share-ui/src/modules/LoginForm/LoginForm.module.css
  q-file-share-ui/src/modules/LoginForm/index.tsx
  q-file-share-ui/src/modules/NavBar/NavBar.module.css
  q-file-share-ui/src/modules/NavBar/index.tsx
  q-file-share-ui/src/modules/SignUpForm/SignUpForm.module.css
  q-file-share-ui/src/modules/SignUpForm/index.tsx
Labels: enhancement, front-end
